node-gradle/gradle-node-plugin

src/main/groovy/com/moowork/gradle/node/task/SetupTask.groovy, src/main/groovy/com/moowork/gradle/node/util/BackwardsCompat.groovy
make use of patternLayout instead of layout 'pattern' on gradle 5.0 and later to ensure compatibilty with gradle 6.0
fixes node-gradle/gradle-node-plugin#2 respectively
srs/gradle-node-plugin#316
Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>
=> make use of patternLayout instead of layout 'pattern' on gradle 5.0 and later to ensure compatibilty with gradle 6.0

src/main/groovy/com/moowork/gradle/node/npm/NpxTask.groovy
I saw that the commit 30c13c29cca3c9820b2aa501aa3e96600b5d11cb introduces a constant for the name of the task group. This make me think that I did not set the group in the NpxTask. Here it is!
=> Set the node group to the npx task

src/test/groovy/com/moowork/gradle/AbstractIntegTest.groovy
I added this change each time I had to debug an integration test when working on the NpxTask pull request. I did not commit it but I think that would make sense to do it. I don't think that has any unwanted side-effect.
What do you think about that?
=> Print the output of the integration test builds so that we can access it in the test reports

gradle/wrapper/gradle-wrapper.properties, gradlew, src/test/groovy/com/moowork/gradle/AbstractIntegTest.groovy, src/test/groovy/com/moowork/gradle/RunWithMultipleGradleVersions.groovy, src/test/groovy/com/moowork/gradle/RunWithMultipleGradleVersionsExtension.groovy
This pull request changes the test execution flow in order to get them executed on multiple Gradle versions (`5.0` and `5.6.2` for now) as requested in issue #4 .
It works but it dramatically increases the tests execution time. What else could we expect?
Do you think running with the lowest and highest supported version is a good choice? Do you think some tests would require to be also executed on specific intermediate versions?
Also, I could not get the iteration (the fact of running multiple times the same method with different configurations) name work. It prints the Gradle version in the Gradle output in order to easily know which version corresponds to iterations `0` and `1` (default naming).
I can adapt the Spock extension according to your feedback.
=> Run integration tests with multiple Gradle versions

src/main/groovy/com/moowork/gradle/node/task/SetupTask.groovy
Fixes the `npx` symlink so that `NpxTask` works correctly (on mac)
=> Fixed symlink for npx

src/main/kotlin/com/moowork/gradle/node/task/SetupTask.kt
Similar rationale as https://github.com/srs/gradle-node-plugin/commit/5a392ad45968da29c341404116fa907d41756b2c
We want to be able to make use of the unpacked node distribution in a place where the filesystem mapping is different, but seems this change didn't make it across to the kotlin rewrite.
=> relativize npm and npx symlinks

src/main/kotlin/com/github/gradle/node/npm/exec/NpmExecRunner.kt, src/main/kotlin/com/github/gradle/node/npm/proxy/NpmProxy.kt, src/main/kotlin/com/github/gradle/node/yarn/exec/YarnExecRunner.kt, src/test/groovy/com/github/gradle/AbstractIntegTest.groovy, src/test/groovy/com/github/gradle/node/npm/task/NpmInstallTaskTest.groovy, src/test/groovy/com/github/gradle/node/npm/task/NpmProxy_integTest.groovy, src/test/groovy/com/github/gradle/node/npm/task/NpmTaskTest.groovy, src/test/groovy/com/github/gradle/node/yarn/task/YarnProxy_integTest.groovy, src/test/groovy/com/github/gradle/node/yarn/task/YarnTaskTest.groovy, src/test/kotlin/com/github/gradle/node/npm/proxy/NpmProxyTest.kt, src/test/resources/fixtures/javascript-project/package.json
* Makes the URL in `HTTP_PROXY` and `HTTPS_PROXY` into `http://` to match the most common setup.
* Prevents automatic proxy configuration if there's already existing proxy configuration in environment variables
=> Automatic proxy configuration fixes for  #113

src/main/kotlin/com/github/gradle/node/npm/task/NpmSetupTask.kt, src/main/kotlin/com/github/gradle/node/yarn/task/YarnSetupTask.kt, src/test/groovy/com/github/gradle/node/npm/task/NpmInstall_integTest.groovy, src/test/groovy/com/github/gradle/node/yarn/task/YarnInstall_integTest.groovy
This adds a simple test for npm and yarn that checks that installation works on npm 7 and greater.
It's `download = true` to make sure that we run on new enough versions.
=> Add tests and support for npm >= 7 fixes #123

.github/workflows/build.yml, build.gradle.kts, src/test/groovy/com/github/gradle/RunWithMultipleGradleVersionsExtension.groovy
This is to cut down on test time on Windows.
I've seen many cases where Windows takes 330+ minutes to finish, so I'm adding properties to toggle which version to test.
And changing Windows to only test `Current` and `Oldest supporter` (5.6.4)
=> Add properties to toggle which Gradle versions to integration test.

docs/installation.md
The `gradlePluginPortal()` function is used directly within the repositories block, not within a maven block.
=> Installation instructions: Fix repositories block

src/main/kotlin/com/github/gradle/node/util/PlatformHelper.kt, src/test/groovy/com/github/gradle/node/util/PlatformHelperTest.groovy
This moves the `uname -m` into the property `uname` to let us test the functionality on non-arm systems.
=> Add tests for PlatformHelper arm functionality.

docs/faq.md, docs/usage.md, src/main/kotlin/com/github/gradle/node/NodeExtension.kt, src/main/kotlin/com/github/gradle/node/NodePlugin.kt, src/main/kotlin/com/github/gradle/node/npm/exec/NpmExecRunner.kt, src/main/kotlin/com/github/gradle/node/npm/proxy/NpmProxy.kt, src/main/kotlin/com/github/gradle/node/npm/proxy/ProxySetting.kt, src/main/kotlin/com/github/gradle/node/npm/proxy/ProxySettings.kt, src/main/kotlin/com/github/gradle/node/yarn/exec/YarnExecRunner.kt, src/test/groovy/com/github/gradle/node/npm/task/NpmInstallTaskTest.groovy, src/test/groovy/com/github/gradle/node/npm/task/NpmTaskTest.groovy, src/test/groovy/com/github/gradle/node/yarn/task/YarnSetupTaskTest.groovy, src/test/groovy/com/github/gradle/node/yarn/task/YarnTaskTest.groovy, src/test/kotlin/com/github/gradle/node/npm/proxy/NpmProxyTest.kt, src/test/resources/fixtures/kotlin/build.gradle.kts
This replaces the proxy setting with an enum containing:
- `SMART` (previous `true`)
- `FORCED` (always apply)
- `OFF` (previous `false`)
=> Replace proxy settings with an enum.

docs/faq.md
I'm not a Gradle expert but the present `args = argus + …` results in
```
* What went wrong:
Execution failed for task ':navigation-feedback-ui:npmSetup'.
> No signature of method: org.gradle.api.internal.provider.DefaultListProperty.plus() is applicable for argument types: (ArrayList) values: [[--registry, http://myregistry.npm.com]]
Possible solutions: value(java.lang.Iterable), value(org.gradle.api.provider.Provider), value(java.lang.Iterable), value(org.gradle.api.provider.Provider), split(groovy.lang.Closure), use([Ljava.lang.Object;)
```
=> Update FAQ to be compatible with version 3.0.1

src/main/kotlin/com/github/gradle/node/exec/ExecConfiguration.kt, src/main/kotlin/com/github/gradle/node/exec/ExecRunner.kt, src/main/kotlin/com/github/gradle/node/exec/NodeExecConfiguration.kt, src/main/kotlin/com/github/gradle/node/exec/NodeExecRunner.kt, src/main/kotlin/com/github/gradle/node/npm/exec/NpmExecRunner.kt, src/main/kotlin/com/github/gradle/node/npm/proxy/NpmProxy.kt, src/main/kotlin/com/github/gradle/node/util/ProjectApiHelper.kt, src/main/kotlin/com/github/gradle/node/variant/VariantComputer.kt, src/main/kotlin/com/github/gradle/node/yarn/exec/YarnExecRunner.kt, src/test/groovy/com/github/gradle/node/SystemVersion_integTest.groovy, src/test/groovy/com/github/gradle/node/npm/task/NpmInstall_integTest.groovy, src/test/resources/fixtures/node-system-version/build.gradle
Make the `ExecRunners` (and depending classes) public to allow for external users to use these to extend functionality.
This is the simpler solution compared to subclassing the tasks
=> Open utility classes for external consumption.

.github/workflows/build.yml, build.gradle.kts, src/main/kotlin/com/github/gradle/node/NodePlugin.kt, src/main/kotlin/com/github/gradle/node/exec/NodeExecRunner.kt, src/main/kotlin/com/github/gradle/node/npm/exec/NpmExecRunner.kt, src/main/kotlin/com/github/gradle/node/npm/task/NpmSetupTask.kt, src/main/kotlin/com/github/gradle/node/npm/task/NpmTask.kt, src/main/kotlin/com/github/gradle/node/npm/task/NpxTask.kt, src/main/kotlin/com/github/gradle/node/task/BaseTask.kt, src/main/kotlin/com/github/gradle/node/task/NodeSetupTask.kt, src/main/kotlin/com/github/gradle/node/task/NodeTask.kt, src/main/kotlin/com/github/gradle/node/util/PlatformHelper.kt, src/main/kotlin/com/github/gradle/node/variant/VariantComputer.kt, src/main/kotlin/com/github/gradle/node/yarn/exec/YarnExecRunner.kt, src/main/kotlin/com/github/gradle/node/yarn/task/YarnSetupTask.kt, src/main/kotlin/com/github/gradle/node/yarn/task/YarnTask.kt, src/test/groovy/com/github/gradle/RunWithMultipleGradleVersionsExtension.groovy, src/test/groovy/com/github/gradle/node/npm/task/NpmInstallTaskTest.groovy, src/test/groovy/com/github/gradle/node/npm/task/NpmProxy_integTest.groovy, src/test/groovy/com/github/gradle/node/npm/task/NpmSetupTaskTest.groovy, src/test/groovy/com/github/gradle/node/npm/task/NpmTaskTest.groovy, src/test/groovy/com/github/gradle/node/npm/task/NpxTaskTest.groovy, src/test/groovy/com/github/gradle/node/task/AbstractTaskTest.groovy, src/test/groovy/com/github/gradle/node/task/NodeTaskTest.groovy, src/test/groovy/com/github/gradle/node/util/PlatformHelperTest.groovy, src/test/groovy/com/github/gradle/node/util/TestablePlatformHelper.groovy, src/test/groovy/com/github/gradle/node/variant/VariantComputerTest.groovy, src/test/groovy/com/github/gradle/node/yarn/task/YarnProxy_integTest.groovy, src/test/groovy/com/github/gradle/node/yarn/task/YarnTaskTest.groovy
- Removed the `props` variable in `PlatformHelper` to avoid failures in 7.4
- Refactored use of PlatformHelper.INSTANCE just to tasks, the task then passes down its helper instance for Runner / VariantComputer use
- Added a new BaseTask class to hold common properties across all tasks, since PlatformHelper.INSTANCE isn't used anymore
- Tweaked some tests to use the Task sourced PlatformHelper, making execution deterministic and avoiding race conditions, no need for racey originalPlatformHelper anymore. Can probably run more tests in parallel now?
- Tweaked the proxy test server stuff to pass, non-secure would throw 404 for me, can likely back this out with more context. Also tweaked the request verification to be less fragile, was failing for me.
=> Support Gradle 7.4 configuration caching

docs/usage.md, src/test/resources/fixtures/kotlin/build.gradle.kts
This pull request sets the default valio of "version" to the latest node LTS version (16.14.0)
=> adapts the default node version to the latest LTS version

docs/usage.md
This PR adapts the "usage.md" documentation to make use of the current version of this pulugin (3.2.1) instead of 3.0.1
=> adapts usage.md to contain current version

docs/faq.md
Resolves #253 by fixing FAQ docs regarding specifying setup registries, to one that will work with other package managers.
=> Fix FAQ: Specify custom registry for setup

.github/workflows/build.yml, CHANGELOG.md, README.md, build.gradle.kts, gradle.properties, src/main/kotlin/com/github/gradle/node/NodePlugin.kt, src/main/kotlin/com/github/gradle/node/PackageJsonExtension.kt, src/main/kotlin/com/github/gradle/node/npm/task/NpmSetupTask.kt, src/main/kotlin/com/github/gradle/node/npm/task/NpmTask.kt, src/main/kotlin/com/github/gradle/node/npm/task/NpxTask.kt, src/main/kotlin/com/github/gradle/node/pnpm/task/PnpmSetupTask.kt, src/main/kotlin/com/github/gradle/node/pnpm/task/PnpmTask.kt, src/main/kotlin/com/github/gradle/node/task/BaseTask.kt, src/main/kotlin/com/github/gradle/node/task/NodeSetupTask.kt, src/main/kotlin/com/github/gradle/node/task/NodeTask.kt, src/main/kotlin/com/github/gradle/node/util/KotlinUtils.kt, src/main/kotlin/com/github/gradle/node/util/NodeVersionSource.kt, src/main/kotlin/com/github/gradle/node/util/PlatformHelper.kt, src/main/kotlin/com/github/gradle/node/util/ProjectApiHelper.kt, src/main/kotlin/com/github/gradle/node/variant/VariantComputer.kt, src/main/kotlin/com/github/gradle/node/yarn/task/YarnTask.kt, src/test/groovy/com/github/gradle/node/PackageJsonExtensionTest.groovy, src/test/groovy/com/github/gradle/node/npm/task/NpxTask_integTest.groovy, src/test/groovy/com/github/gradle/node/task/NodeSetupTask_integTest.groovy, src/test/groovy/com/github/gradle/node/task/NodeTask_integTest.groovy, src/test/resources/fixtures/npx-env/build.gradle
=> Fix 8.1 configuration-cache support

.github/workflows/build-examples.yml, .github/workflows/build.yml, .github/workflows/publish.yml, CHANGELOG.md, src/main/kotlin/com/github/gradle/node/variant/VariantComputer.kt, src/main/kotlin/com/github/gradle/node/yarn/exec/YarnExecRunner.kt
=> Always use downloaded Yarn as per documentation

src/main/kotlin/com/github/gradle/node/task/NodeTask.kt
With https://github.com/node-gradle/gradle-node-plugin/issues/237 all tasks except for NodeTask had `result` restored
=> Add missing `result` to NodeTask

build.gradle.kts, src/main/kotlin/com/github/gradle/node/NodeExtension.kt, src/main/kotlin/com/github/gradle/node/NodePlugin.kt, src/main/kotlin/com/github/gradle/node/bun/BunSetupTask.kt, src/main/kotlin/com/github/gradle/node/bun/BunTask.kt, src/main/kotlin/com/github/gradle/node/bun/exec/BunExecRunner.kt, src/main/kotlin/com/github/gradle/node/bun/task/BunAbstractTask.kt, src/main/kotlin/com/github/gradle/node/bun/task/BunInstallTask.kt, src/main/kotlin/com/github/gradle/node/bun/task/BunSetupTask.kt, src/main/kotlin/com/github/gradle/node/bun/task/BunTask.kt, src/main/kotlin/com/github/gradle/node/bun/task/BunxTask.kt, src/main/kotlin/com/github/gradle/node/variant/VariantComputer.kt, src/test/groovy/com/github/gradle/node/bun/task/BunInstall_integTest.groovy, src/test/groovy/com/github/gradle/node/bun/task/BunSetupTaskTest.groovy, src/test/groovy/com/github/gradle/node/bun/task/BunTaskTest.groovy, src/test/groovy/com/github/gradle/node/bun/task/BunTask_integTest.groovy, src/test/groovy/com/github/gradle/node/bun/task/Bun_integTest.groovy, src/test/groovy/com/github/gradle/node/bun/task/BunxTask_integTest.groovy, src/test/resources/fixtures/bun-env/build.gradle, src/test/resources/fixtures/bun-env/package.json, src/test/resources/fixtures/bun-in-subdirectory/build.gradle, src/test/resources/fixtures/bun-present/package.json, src/test/resources/fixtures/bun/build.gradle, src/test/resources/fixtures/bunx-env/build.gradle, src/test/resources/fixtures/bunx/build.gradle
Hi, I was thinking about developing a standalone bun gradle plugin, but stumbled upon this issue (https://github.com/node-gradle/gradle-node-plugin/issues/288) and thought that I can give it a try. 
For now, it's WIP but I tested it out and installing bun and running it somewhat works. Still, there probably will be a lot more stuff to be done. If you have any suggestion/pointers I will gladly take any advice - at this state it's basically a copy of pnpm/yarn setup.
And there is one major issue: bun is not yet supported on windows :( Normally I would work around it by using WSL but I'm not sure how's that gonna play with the rest of the code. So I guess windows support would be out of scope in this PR
=> Bun support

src/main/kotlin/com/github/gradle/node/bun/exec/BunExecRunner.kt, src/main/kotlin/com/github/gradle/node/variant/VariantComputer.kt, src/test/groovy/com/github/gradle/node/bun/BunUtils.groovy, src/test/groovy/com/github/gradle/node/bun/task/BunInstall_integTest.groovy, src/test/groovy/com/github/gradle/node/bun/task/BunTask_integTest.groovy, src/test/groovy/com/github/gradle/node/bun/task/BunxTask_integTest.groovy, src/test/groovy/com/github/gradle/node/variant/VariantComputerTest.groovy, src/test/resources/fixtures/bun-env/build.gradle, src/test/resources/fixtures/bun-in-subdirectory/build.gradle, src/test/resources/fixtures/bun/build.gradle, src/test/resources/fixtures/bunx-env/build.gradle, src/test/resources/fixtures/bunx/build.gradle
=> Bun initial cleanup

CHANGELOG.md, src/main/kotlin/com/github/gradle/node/NodePlugin.kt, src/main/kotlin/com/github/gradle/node/util/PlatformHelper.kt, src/test/groovy/com/github/gradle/node/util/PlatformHelperTest.groovy
This adds initial support for ARM64 #315, but it's slightly limited as I couldn't get acquire a compatible device.
The powershell invocation is somewhat slow (sometimes taking almost 700ms with my profile), which is unfortunate because it'd be way smoother to parse than the current `os.arch` solution
The parsing is going to need some additional refactors, but this at least contains the FreeBSD-sins to a single line (which hopefully makes #178 easier to solve)
=> Add support for ARM64 Windows
